# Setup
title:        Cmaketopians
project:      Cmaketopia
tagline:      Go ahead and never say die!
baseurl:      "/Cmaketopia"
#paginate:     1
locale:       "en-GB"

# About/contact
author:
  name:       UncleCShark
  mail:       mailto:unclecshark@gmail.com
  url:        https://github.com/UncleCShark
  repository: https://github.com/UncleCShark/Cmaketopia
  leftlink:   https://unclecshark.github.io/
  rightlink:  https://github.com/unclecshark
  leftimage:  https://user-images.githubusercontent.com/38818698/51142223-9735a580-184b-11e9-928a-eebcb8a0a857.png
  rightimage: https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png
  badge:      https://user-images.githubusercontent.com/38818698/51199406-ec7ac100-18f6-11e9-97f9-d6024a9f66d1.png

# Plugins
plugins:
  - jekyll-relative-links
  - jemoji
#  - jekyll-paginate

# Google Analytics
google_analytics: UA-132222639-1

#Others
markdown: kramdown

#theme: jekyll-theme-cayman
